all:    add_chk_ovr.bin dadd.bin sub.bin tally.bin

add_chk_ovr.bin:     add_chk_ovr.pa
	palbart $<

dadd.bin:               dadd.pa
	palbart $<

sub.bin:                sub.pa
	palbart $<
 
tally.bin:	tally.pa
	palbart $<

clean:
	@rm -f *.lst *.bin *.rim
