all:    add_chk_ovr.bin dadd.bin dsub.bin mult8.bin sub.bin tally.bin

add_chk_ovr.bin:     add_chk_ovr.pa
	palbart $<

dadd.bin:               dadd.pa
	palbart $<

dsub.bin:               dsub.pa
	palbart $<

sub.bin:                sub.pa
	palbart $<
 
mult8.bin:              mult8.pa
	palbart $<
 
tally.bin:	        tally.pa
	palbart $<

clean:
	@rm -f *.lst *.bin *.rim
